<script>
    window.PAGE_ADMIN_CONFIG = {
        pageTree: <?= $treeJson ?>,
        apiUrl: 'api/pages.php',
        csrfToken: <?= json_encode(getCsrfToken(), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>,
        lang: <?= json_encode([
            'loading' => __('loading'),
            'error_loading' => __('error_loading'),
            'error_network' => __('error_network'),
            'system_error' => __('system_error'),
            'history_empty' => __('history_empty'),
            'current_version' => __('current_version'),
            'no_details' => __('no_details'),
            'preview' => __('preview'),
            'restore' => __('restore'),
            'restore_confirm' => __('restore_confirm'),
            'restore_success' => __('restore_success'),
            'error_prefix' => __('error_prefix'),
            'added' => __('added'),
            'changed' => __('changed'),
            'deleted' => __('deleted'),
            'title' => __('title'),
            'image' => __('image'),
            'template' => __('post_template'),
            'parent_page' => __('parent_page'),
            'changed_title' => __('changed_title'),
            'changed_url' => __('changed_url'),
            'changed_template' => __('changed_template'),
            'changed_parent_page' => __('changed_parent_page'),
            'page_activated' => __('page_activated'),
            'page_deactivated' => __('page_deactivated'),
            'set_homepage' => __('set_homepage'),
            'unset_homepage' => __('unset_homepage'),
            'initial_version' => __('initial_version'),
            'no_changes' => __('no_changes'),
            'changed_seo_title' => __('changed_seo_title'),
            'changed_seo_desc' => __('changed_seo_desc'),
            'add_dir' => __('add_dir'),
            'edit_dir' => __('edit_dir'),
            'delete_directory_confirm' => __('delete_directory_confirm'),
            'delete_page_confirm' => __('delete_page_confirm'),
            'delete_directory_with_pages' => __('delete_directory_with_pages'),
            'copy_page_confirm' => __('copy_page_confirm'),
            'set_homepage_confirm' => __('set_homepage_confirm'),
            'homepage_changed' => __('homepage_changed'),
            'error_copy_url' => __('error_copy_url'),
            'active_tooltip' => __('active_tooltip'),
            'inactive_tooltip' => __('inactive_tooltip'),
            'url' => __('new_url'),
        ]) ?>,
        icons: <?= json_encode([
            'toggleActive' => getToggleIcon(true),
            'toggleInactive' => getToggleIcon(false),
            'starActive' => getStarIcon(true),
            'starInactive' => getStarIcon(false),
        ]) ?>
    };
    window.CLIPON_CSRF_TOKEN = window.PAGE_ADMIN_CONFIG.csrfToken;
</script>
